language: python
python:
  - 2.7
  - 3.5

services:
  - docker

install:
  - docker build -t soptbot .

# command to install dependencies
before_script:
    -  pip install -r requirements-dev.txt
  
# command to run tests
script:
  - flake8 .
  - pytest
